language: elixir
elixir:
  - 1.10.4
  - 1.11.2
  - 1.13.4
  - 1.14.2
otp_release:
  - 22.2
  - 23.0
  - 24.0
  - 25.0
matrix:
  exclude:
    - elixir: 1.9.4
      otp_release: 23.0
sudo: false
script:
  - mix test
  - mix espec
  - mix espec spec_formatters/test_spec.exs
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.13.4" ]; then mix format --check-formatted; fi
  - mix espec --stale
notifications:
  recipients:
    - anton.mishchuk@gmail.com
