language: elixir
elixir:
  - 1.6.6
  - 1.7.2
  - 1.8.1
otp_release:
  - 19.3
  - 20.3
  - 21.3
matrix:
  exclude:
    - elixir: 1.8.1
      otp_release: 19.3
    - elixir: 1.6.0
      otp_release: 21.3

sudo: false
script:
  - mix test
  - mix espec
  - mix espec spec_formatters/test_spec.exs
notifications:
  recipients:
    - anton.mishchuk@gmail.com
