name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - otp-version: '22.0'
            elixir-version: '1.11'
          - otp-version: '23.0'
            elixir-version: '1.13'
          - otp-version: '24.0'
            elixir-version: '1.13'
          - otp-version: '24.0'
            elixir-version: '1.14'
          - otp-version: '25.0'
            elixir-version: '1.13'
          - otp-version: '25.0'
            elixir-version: '1.14'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      env:
        ImageOS: ubuntu20
      with:
        elixir-version: ${{matrix.pair.otp-version}}
        otp-version: ${{matrix.pair.elixir-version}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Run tests with espec
      run: mix espec
    - name: Run formatters
      run: mix espec spec_formatters/test_spec.exs

